#ifndef BEACON_IMAGE_CONFIG_H_
#define BEACON_IMAGE_CONFIG_H_

/* Normal threshold used for beacon segmentation after car-lamp masking. */
#define BEACON_BINARY_THRESHOLD       200
#define BEACON_BEACON_LOW_THRESHOLD   150
#define BEACON_BEACON_TINY_THRESHOLD  130
#define BEACON_BEACON_MICRO_THRESHOLD 100

/* High threshold used to isolate the very bright car lamp strip. */
#define BEACON_CAR_LAMP_THRESHOLD     200

/* Connected-component area filters. */
#define BEACON_MIN_COMPONENT_AREA     8
#define BEACON_MAX_COMPONENT_AREA     5000
#define BEACON_MIN_LAMP_AREA          24
#define BEACON_MAX_LAMP_AREA          1200
#define BEACON_MIN_LAMP_ELONGATION    1.6f
#define BEACON_MIN_LAMP_LENGTH        8.0f
#define BEACON_LAMP_TRACK_START_AREA  45
#define BEACON_LAMP_TRACK_START_ELONGATION 2.0f
#define BEACON_LAMP_TRACK_START_SCORE 120.0f
#define BEACON_STRONG_LAMP_AREA       45
#define BEACON_SMALL_LAMP_MIN_SPAN    12
#define BEACON_SMALL_LAMP_BACKGROUND_MAX 60
#define BEACON_LAMP_MASK_PAD          4
#define BEACON_LAMP_COMPANION_ELONGATION 1.6f
#define BEACON_LAMP_COMPANION_DISTANCE 36.0f
#define BEACON_EDGE_LAMP_BACKGROUND_MAX 80
#define BEACON_SIDE_SUN_LAMP_BACKGROUND_MAX 70
#define BEACON_SIDE_SUN_LAMP_MARGIN  16
#define BEACON_SIDE_SUN_LAMP_Y       36
#define BEACON_TOP_SUN_LAMP_BACKGROUND_MAX 84
#define BEACON_TOP_SUN_LAMP_Y        18
#define BEACON_EDGE_LAMP_MIN_AREA     18
#define BEACON_EDGE_LAMP_MARGIN       2
#define BEACON_EDGE_LAMP_MIN_SPAN     5
#define BEACON_MAX_BEACON_AREA        260
#define BEACON_MAX_BEACON_ELONGATION  2.8f
#define BEACON_TOP_BEACON_Y           24.0f
#define BEACON_TOP_BEACON_MIN_AREA    3
#define BEACON_TOP_BEACON_MAX_AREA    48
#define BEACON_TOP_BEACON_MAX_ELONGATION 3.4f
#define BEACON_MID_BEACON_Y           56.0f
#define BEACON_MID_BEACON_MAX_AREA    150
#define BEACON_LAMP_RESIDUE_ELONGATION 1.65f
#define BEACON_LAMP_RESIDUE_DISTANCE  24.0f
#define BEACON_EDGE_BEACON_MIN_AREA   8
#define BEACON_EDGE_BEACON_MAX_AREA   90
#define BEACON_EDGE_BEACON_MAX_SPAN   18
#define BEACON_EDGE_BEACON_MARGIN     1
#define BEACON_NO_LAMP_SMALL_AREA     80
#define BEACON_NO_LAMP_SMALL_ELONGATION 1.5f
#define BEACON_DARK_SMALL_BACKGROUND_MAX 30
#define BEACON_LOCAL_CONTRAST_AREA    40
#define BEACON_LAMP_TINY_Y            40.0f
#define BEACON_LAMP_TINY_MAX_AREA     6
#define BEACON_LAMP_TINY_BACKGROUND_MAX 30
#define BEACON_LAMP_MICRO_MAX_AREA    8
#define BEACON_LAMP_MICRO_BACKGROUND_MAX 25
#define BEACON_LOCAL_RING_PAD         3
#define BEACON_LOCAL_BACKGROUND_MAX   50
#define BEACON_NEW_SLOT_MIN_AREA      3
#define BEACON_NEW_SLOT_MAX_ELONGATION 3.4f
#define BEACON_NEW_SLOT_EDGE_MARGIN   1
#define BEACON_LAMP_CONTEXT_FRAMES    12
#define BEACON_NEW_SLOT_FRAMES_AFTER_LAMP 120
#define BEACON_LAMP_LOST_BEACON_MIN_Y 100.0f
#define BEACON_LAMP_NEW_SLOT_NEAR_AREA 28
#define BEACON_LAMP_NEW_SLOT_DISTANCE 32.0f
#define BEACON_LAMP_NEW_SLOT_EDGE_MARGIN 4
#define BEACON_TRACKED_SLOT_LIMIT     4
#define BEACON_DUPLICATE_DISTANCE     5.0f
#define BEACON_TRACK_MATCH_DISTANCE   36.0f

/* Queue size = image pixel count. */
#define BEACON_QUEUE_SIZE             (BEACON_IMAGE_W * BEACON_IMAGE_H)

#endif
